python3.9:
    stage: test
    tags: [ci.inria.fr]
    image: python:3.9
    script:
    - pip install tox
    - tox -e py39

pep8:
    stage: test
    tags: [ci.inria.fr]
    image: python:3.9
    script:
    - pip install tox
    - tox -e pep8


#### Entering the release zone
pages:
    stage: deploy
    tags: [ci.inria.fr]
    image: python:3.9
    only:
    - tags
    script:
    - tox -e docs
    - mkdir -p public/
    - cp -r docs/_build/html/* public/
    artifacts:
      paths:
      - public

pypi:
    stage: deploy
    tags: [ci.inria.fr]
    image: python:3.9
    only:
    - tags
    script:
    - python setup.py bdist_wheel
    - pip install twine
    # credentials are set in the env by gitlab
    - twine upload dist/* --verbose
