---
# https://serverfault.com/questions/881517/why-disable-swap-on-kubernetes
- name: Disable swap
  command: swapoff -a

- name: Allow root login by setting PermitRootLogin to yes
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin yes'
    state: present

- name: Restart SSH service
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install Openshift client (for k8s module)
  pip:
    name: openshift
    state: present

- include: "g5k.yml"
  when: context == "g5k"
